version: "3.6"
services:
  tf:
    # http://10.4.1.245:6884
    build: .
    shm_size: 20GB 
    # image: fastai/fastai:2022-05-29 
    # image: xx___pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime
    ports:
      - "6885:8888"
    volumes:
      - ../mla:/crib/mla
      #- ../ir4:/crib/ir4
      - ../imgdata:/crib/imgdata
      #- ./workspace:/workspace
      - ./home/dot/jupyter:/root/.jupyter
    working_dir: /crib/mla

    command: ["bash", "-c", "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/crib --ip 0.0.0.0 --no-browser --allow-root"]  

    # keep container running..
    # command: tail -f /dev/null
    # command: /bin/bash -c "pwd && /bin/bash"
    # tty: true

